spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/creditmanager
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: false

jwt:
  secret: 12345678901234567890123456789012

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test