spring:
  datasource:
    url: jdbc:h2:~/data/creditmanager
  jpa:
    show-sql: true
    ddl-auto: update

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password:
#    url: jdbc:mysql://knu-credit.csccnv3led8h.ap-northeast-2.rds.amazonaws.com:3306/credit_knu?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    username:
#  jpa:
#    database: mysql
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update

jwt:
  secret: 12345678901234567890123456789012

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test