spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/creditmanager
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    ddl-auto: create

jwt:
  secret: 12345678901234567890123456789012

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test